/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface FindByFilter$Params {
  searchedTerm: string;
  limit: number;
  offset: number;
  filterType: string;
  listenedIds: string;
}

export function findByFilter(http: HttpClient, rootUrl: string, params: FindByFilter$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, findByFilter.PATH, 'get');
  if (params) {
    rb.query('searchedTerm', params.searchedTerm, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
    rb.query('filterType', params.filterType, {});
    rb.query('listenedIds', params.listenedIds, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

findByFilter.PATH = '/messages/filter';
