/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NewMessage } from '../../models/new-message';

export interface MessagesPost$Params {
      body: NewMessage
}

export function messagesPost(http: HttpClient, rootUrl: string, params: MessagesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'status'?: string;
}>> {
  const rb = new RequestBuilder(rootUrl, messagesPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'status'?: string;
      }>;
    })
  );
}

messagesPost.PATH = '/messages';
