/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MessagesFilterGet$Params {
  speaker?: number;
  book?: number;
  dateFrom?: Date;
}

export function messagesFilterGet(http: HttpClient, rootUrl: string, params?: MessagesFilterGet$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, messagesFilterGet.PATH, 'get');
  if (params) {
    rb.query('speaker', params.speaker, {});
    rb.query('book', params.book, {});
    rb.query('dateFrom', params.dateFrom, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

messagesFilterGet.PATH = '/messages/filter';
