/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Book } from './models/book';
export type { ErrorsSchema } from './models/errors-schema';
export type { Message } from './models/message';
export type { MessageType } from './models/message-type';
export type { NewMessage } from './models/new-message';
export type { Speaker } from './models/speaker';
