/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AudioFileService } from './services/audio-file.service';
export { BookService } from './services/book.service';
export { MessageService } from './services/message.service';
export { MessageTypesService } from './services/message-types.service';
export { SpeakerService } from './services/speaker.service';
