/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Book } from '../models/book';
import { MessageType } from '../models/message-type';
import { Speaker } from '../models/speaker';
export interface Message {
  book?: Book;
  date?: Date;
  id?: number;
  image?: string;
  messageType?: MessageType;
  mimetype?: string;
  normalizedTitle?: string;
  note?: string;
  questions?: string;
  speaker?: Speaker;
  title?: string;
  url?: string;
  verses?: string;
}
