/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NewMessage {
  date: Date;
  idBook: number;
  idMessageType: number;
  idSpeaker: number;
  mimetype?: string;
  normalizedTitle: string;
  note?: string;
  questions?: string;
  title: string;
  url: string;
  verses?: string;
}
