/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NewMessage {
  date: Date;
  id_book: number;
  id_message_type: number;
  id_speaker: number;
  mimetype?: string;
  normalized_title: string;
  note?: string;
  questions?: string;
  title: string;
  url: string;
  verses?: string;
}
