/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAudio } from '../fn/audio-file/get-audio';
import { GetAudio$Params } from '../fn/audio-file/get-audio';

@Injectable({ providedIn: 'root' })
export class AudioFileService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAudio()` */
  static readonly GetAudioPath = '/audioFiles';

  /**
   * Get audio from url.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAudio()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAudio$Response(params: GetAudio$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return getAudio(this.http, this.rootUrl, params, context);
  }

  /**
   * Get audio from url.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAudio$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAudio(params: GetAudio$Params, context?: HttpContext): Observable<Blob> {
    return this.getAudio$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

}
