/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getMessageTypes } from '../fn/message-types/get-message-types';
import { GetMessageTypes$Params } from '../fn/message-types/get-message-types';
import { MessageType } from '../models/message-type';

@Injectable({ providedIn: 'root' })
export class MessageTypesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getMessageTypes()` */
  static readonly GetMessageTypesPath = '/messageTypes';

  /**
   * Get a list of all message types.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMessageTypes()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMessageTypes$Response(params?: GetMessageTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'messageTypeList'?: Array<MessageType>;
}>> {
    return getMessageTypes(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of all message types.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMessageTypes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMessageTypes(params?: GetMessageTypes$Params, context?: HttpContext): Observable<{
'messageTypeList'?: Array<MessageType>;
}> {
    return this.getMessageTypes$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'messageTypeList'?: Array<MessageType>;
}>): {
'messageTypeList'?: Array<MessageType>;
} => r.body)
    );
  }

}
