# npx trapeze run config.yaml --android-project android
vars:
  BUNDLE_ID:
    default: io.my.church
  PACKAGE_NAME:
    default: io.my.church

platforms:
  android:
    packageName: $PACKAGE_NAME
    versionName: 1.3.1
    versionCode: 100301
    manifest:
      - file: AndroidManifest.xml
        target: manifest/application
        inject:
          <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
          <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

    res:
      - path: drawable
        file: icon.png
        source: ./resources/icon.png