# npx trapeze run config.yaml --android-project android
vars:
  BUNDLE_ID:
    default: io.my.church
  PACKAGE_NAME:
    default: io.my.church

platforms:
  android:
    packageName: $PACKAGE_NAME
    versionName: 1.3.2
    versionCode: 100302

    res:
      - path: drawable
        file: icon.png
        source: ./resources/icon.png